#!/usr/bin/env lua
-- vim: ft=lua ts=2 sw=2 sts=2 et:cindent:formatoptions+=cro
--------- --------- --------- --------- --------- --------- 

do 
  local root = '..'
  local seen = {}
  Ide = Ide or os.getenv('Ide') or '/opt/ide'
  function use(f, show)
    if not seen[f] then 
      if show then io.stderr:write('-- ' .. f .. '\n') end
      seen[f] = dofile(Ide .. '/' .. f)
    end 
    return seen[f]
  end 
end

return use
