#!/usr/bin/env lua
-- vim: ft=lua ts=2 sw=2 sts=2 et:cindent:formatoptions+=cro
--------- --------- --------- --------- --------- ---------

if not use then dofile '../use' fi

use 'lib'
use 'ok'

function xxx()
end

-- ## Main 
-- If called as top-level file.

return {main = function() xxx() end}
