#!/usr/bin/env bash

#### begin config
What=${What:-Duo101}
Who=${Who:-Tim Menzies}
When=${When:-2019}
Repo=${Repo:-d-u-o/101}
Lua=$(which luajit)
#### end config

##############################################
trap cleanup  0 1 2 3 6

Tmp=${Tmp:-/tmp/$USER/ide/$$.$RANDOM}
Ide=${Ide:-$(dirname $PWD)}
Etc=${Etc:-"$Ide"/etc}
Src=${Src:-"$Ide"/src}
Bin=${Bin:-$Src}
Doc=${Doc:-"$Ide"/docs}
Test=${Test:-"$Ide"/test}

bashrc()    { cat "$Etc"/dotbashrc;    }
citation()  { . "$Etc"/citation.sh;    }
cleanup()   { rm -rf  "$Tmp";          }
conduct()   { cat "$Etc"/conduct.md;   }
contrib()   { cat "$Etc"/contrib.md;   }
exe()       { chmod +x "$Etc"/*.sh;    }
exists()    { exists0 "$1" $2; git add "$1"; }
exists0()   { if [ ! -f "$1" ]; then $2 > "$1"; fi; }
gitignore() { cat "$Etc"/dotgitignore; }
license()   { . "$Etc"/license.sh;     }
makedirs()  { mkdir -p "$Src" "$Tmp" "$Bin" "$Etc" "$Test" "$Doc"; 
	      echo .nojekyll > "$Doc"/.nojekyll 
	      git add "$Doc"/.nojekyll
            }
requires()  { cat "$Etc"/requires.txt; }
vimrc()     { . "$Etc"/dotvimrc.sh;    }

box="$(uname -s)"
case "${unameOut}" in
    Linux*)     box=Linux;;
    Darwin*)    box=Mac;;
    CYGWIN*)    box=Cygwin;;
    MINGW*)     box=MinGw;;
    *)          box="UNKNOWN:${unameOut}"
esac

if [ "$box" == "Linux" ]; then 
   [ ! `which lua`     ] >&2 && sudo apt-get install lua
   [ ! `which luajit`  ] >&2 && sudo apt-get install luajit
   [ ! `which pycco`   ] >&2 && sudo -H pip install pycco
fi

if [ "$box" == "Mac"  ]; then 
   [ ! `which lua`    ] >&2 && brew lua
   [ ! `which luajit` ] >&2 && brew luajit
   [ ! `which pycco`  ] >&2 && sudo -H pip install pycco
fi

makedirs
exe
exists  "$Ide"/.gitignore          gitignore
exists  "$Ide"/requirements.txt    requires
exists  "$Ide"/CITATION.md         citation
exists  "$Ide"/LICENSE.md          license
exists  "$Ide"/CODE_OF_CONDUCT.md  conduct
exists  "$Ide"/CONTRIBUTING.md     contrib
exists0 "$Tmp"/.vimrc              vimrc
exists0 "$Tmp"/.bashrc             bashrc

for f in $(ls $Src | grep -v '.lua') ; do
  if [ -n "$(sed -n '/usr.bin.env/p;q' $f)" ]; then
    chmod +x $f
  fi
done

Bin="$Bin" Here="$Here" What="$What" Lua="$Lua" \
Who="$Who" When="$When" Repo="$Repo" Doc="$Doc"  \
Ide="$Ide" Tmp="$Tmp"   Etc="$Etc"   Test="$Test" \
Src="$Src"                                         \
bash --init-file "$Tmp"/.bashrc -i
