#!/usr/bin/env bash
# vim: ts=2 sw=2 sts=2 et:cindent:formatoptions+=cro

if [ ! -d "my" ]; then echo "missing 'my'" ; else

_c1="\033[01;32m"
_c2="\033[01;34m"
_c3="\033[31m"
_c6="\033[33m"
_c5="\033[35m$"
_c0="\033[00m"
_c7="\033]01;19"

here() { cd $1; basename "$PWD"; }

ghbranch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}

PROMPT_COMMAND='echo -ne "$(hostname -s)${_c1}$(ghbranch) ${_c6}\033]0;$(here ..)/$(here .)\007";PS1="${_c1}$_c2$(here ..)/$_c3$(here .) ${_c6}\!:${_c0}\e[m "'

alias ls='ls -GF'
alias vi="`which vim` -u $PWD/my/vimrc"
alias get="git pull"
alias put="git commit -am committing; git push; git status"

if [ -n "$1" ];then my/Makefile $1; fi

fi
